# Copyright (c) 2016-2022 Magnusson Institute, All Rights Reserved.

# Setup for MINIFLARE local development of channel server

# setup: copy this file to the top level and rename it 'wrangler.toml'
# see README for further details.

name = "c"

type = "javascript"
workers_dev = false
compatibility_date = "2022-02-01"

# for miniflare you don't need any IDs
kv_namespaces = [
    { binding = "MESSAGES_NAMESPACE", preview_id = "", id ="" },
    { binding = "KEYS_NAMESPACE", preview_id = "", id ="" },
    { binding = "LEDGER_NAMESPACE", preview_id = "", id = "" }
]

[build.upload]
format = "modules"
dir = "src"
main = "./room.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
    { name = "rooms", class_name = "ChatRoomAPI" },
]

[miniflare]
kv_persist = true # Defaults to ./.mf/kv
durable_objects_persist = true # Defaults to ./.mf/do

[vars]
DOCKER_WS="true"
SERVER_SECRET="password"  # this isn't as bad as it looks - all it does is allow somebody to start a new channel
LEDGER_KEY='{"key_ops":["encrypt"],"ext":true,"kty":"RSA","n":"zY029N1LvXigHTDGV0e5yXrBAQ13SWR1ULdl6o3aqExD9H2HAj1p7S9HW17uMe4ScKQ-N8DJkJLwToIkkm8p8__PKoADx4gCGChsx0RYYDIB855vC8mQ6rVGM4goqDhdiNcAxB1icp54KKIBeFzrMQUTqDpErT9s9jKdQeX16eSkSDdCaDTEuyxQq9h0jT3981H-aXucPHtRVNJ0jCMRzVxorzFBBAuU6l5EnTcW-e-Do7S_KWaOFohhlYdSQDPuXpamrZheaZQTxp5Y0C5rx_YctfnJI-tpBF_xTetj3Y_heVSYXyFEZRQlNDUhZYvFktZbjlx0Vu06NFBXm60SjIJ8f82bMfFT59XtuRkKVSZcP0DxvlCwDwiKb-5CkJ2mX-3c_oIu-jdWLkvTXsOo22txEt8lWBzx8xXQmB-LE6-c1IPy6A0ZFPrq-is2UIs8UOH0Na10Ba73Fc1zDxKa2tIux3PdnxRWxFDtyQqUvIAZmpI2NrEytGdiHqJfB-oqsTCuVnmlA9pkdKE4cTWeavDP9K3YHwgocdKKxwqWdONmYF6L2wnPrFOAWiQnq0TOrSSh_ZPh5-vFNLCiWsrGOpFAePVtJ4tdaa_gb23bJcXPOnLb7RDThYVsxK0n-aCzrXvpZkBHfl76vYh9bZ960HRmVB_flCs6l5osRv1pwG0","e":"AQAB","alg":"RSA-OAEP-256"}'

