# Copyright (c) 2023-2024 384(tm) Inc, All Rights Reserved.

# ergo "<name>.<your CF domain>.workers.dev"
name = "channel" # for dev/preview/local

workers_dev = true
compatibility_date =  "2024-01-29"
main = "./src/index.ts"

# Replace with your account id (on the right side of your CF dashboard)
account_id = '....'
usage_model = 'unbound'

# The ledger namespace is shared with the storage server
kv_namespaces = [
  { binding = "MESSAGES_NAMESPACE", id = "...", preview_id = "..." },

  # first one is selected with '--preview false', second one with '--preview'
  # both also exist in '--local' versions (local development)
  { binding = "LEDGER_NAMESPACE", id = "...", preview_id = "..." },

  { binding = "IMAGES_NAMESPACE", id = "...", preview_id = "..." }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChannelServer"]

[[services]]
binding = "STORAGE_SERVER_BINDING"
service = "storage" # needs to be your matching storage server (for history shards)

[durable_objects]
bindings = [
  { name = "channels", class_name = "ChannelServer" },
]

[env.production]
name = "c" # default production channel name eg "c.<your CF domain>.workers.dev"
kv_namespaces = [
  { binding = "MESSAGES_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "LEDGER_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "IMAGES_NAMESPACE", id = "...", preview_id = "..." }
]

[[env.production.services]]
binding = "STORAGE_SERVER_BINDING"
service = "s"

[vars]
VERSION="..."
ENVIRONMENT="development"
STORAGE_SERVER_NAME="storage"
LOG_ERRORS=true
DEBUG_ON=false # low-noise debug output
VERBOSE_ON=false # noisier

# ToDo: separate for dev and prod?
WEB_NOTIFICATION_SERVER = "..."

[env.production.vars]
VERSION="..."
ENVIRONMENT="production"
STORAGE_SERVER_NAME="s"
LOG_ERRORS=true
DEBUG_ON=false
VERBOSE_ON=false
WEB_NOTIFICATION_SERVER = "..."
