# Copyright (c) 2018-2023 Magnusson Institute, All Rights Reserved.

# TODO: it's been a while since we reviewed this ... 

# setup:
# copy this file to the top level and rename it 'wrangler.toml'
# insert the pertinent id:s from Cloudflare dashboard

# Personal Room ('c') Server
# 'c' will be the name on CF, eg "c.<your CF comain>.workers.dev"
name = "c"

type = "javascript"
workers_dev = true
compatibility_date = "2023-05-07"

# Replace with your account id
# From your CF dashboard look to the right side, about midway down you will find your account ID
account_id = '<your Account Id>'

# You need to set up these KV namespaces in the CF dashboard, and
# copy-paste their id:s here. Note that some namespaces are shared
# with the Storage server, in case you're running both.
kv_namespaces = [
  { binding = "MESSAGES_NAMESPACE", id = "<id>" },
  { binding = "KEYS_NAMESPACE", id = "<id>" },
  { binding = "LEDGER_NAMESPACE", id = "<id>" }
]

services = [
  { binding = "notifications", service = "notifications-dev", environment = "production" }
]

[build.upload]
format = "modules"
dir = "src"
main = "./src/index.ts"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
  { name = "channels", class_name = "ChannelServer" },
]

[vars]
STORAGE_SERVER="s"
SERVER_SECRET="...."
LEDGER_KEY='{"key_ops":["encrypt"],"ext":true,"kty":"RSA","n":" .... ","e":"AQAB","alg":"RSA-OAEP-256"}'
