# Copyright (c) 2016-2021 Magnusson Institute, All Rights Reserved.

# setup:
# copy this file to the top level and rename it 'wrangler.toml'
# insert the pertinent id:s from Cloudflare dashboard

# Personal Room ('c') Server
# 'c' will be the name on CF, eg "c.<your CF comain>.workers.dev"
name = "c"

type = "javascript"
workers_dev = true
compatibility_date = "2022-02-01"

# Replace with your account id
# From your CF dashboard look to the right side, about midway down you will find your account ID
account_id = '<your Account Id>'

# You need to set up these KV namespaces in the CF dashboard, and
# copy-paste their id:s here. Note that some namespaces are shared
# with the Storage server, in case you're running both.
kv_namespaces = [
  { binding = "MESSAGES_NAMESPACE", id = "<id>" },
  { binding = "KEYS_NAMESPACE", id = "<id>" },
  { binding = "LEDGER_NAMESPACE", id = "<id>" }
]

[build.upload]
format = "modules"
dir = "src"
main = "./index.js"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
  { name = "channels", class_name = "ChannelServer" },
]
